version: "3.8"
services:
  db :
    build : ./database/
    ports :
      - 5432:5432
    volumes:
      - ./database/create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql
    networks:
        network:
              ipv4_address : 172.20.0.3
      
  pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "5050:80"
        networks:
            network:
              ipv4_address : 172.20.0.2

  app :
    build: ./app/
    networks:
        network:
    depends_on : 
      - db
networks:
  network:
    ipam:
      config:
        - subnet : "172.20.0.0/16"
          gateway: "172.20.0.1"

  
  
  